### ISSUE TITLE
store all Yii::t in database from throughout .php files

### ISSUE THREAD

**Issue by NabiKAZ** [gusnips/yii.translate#2]
In here when visit a page, store all words(in current page) of Yii::t in database, but how can store all words of all .php files in database just by one click, be like yiic message messages/config.php command.
Please provide this feature.
Thanks a lot.

**Comment by gusnips** [comment]
That should be hard to do, because the translations are split in many files in the project folder, and we can't just execute those files, we would need to do a regular expression in all files.
Also, it's a one time thing, so I don't think I should invest time on it for now.
I might reopen if you have another use case I didn't think of
